### ISSUE TITLE
what is the point in the restriction?

### ISSUE THREAD

**Issue by boris-741** [Leopotam/ecs#1]
what is the point in the restriction? can I create more than 256 components?
for example: if I have a field match of 20x20 then how am I supposed to be in this case? plus there is a need to hang some of the same components - jemcomponent

**Comment by Leopotam** [comment]
256 **different** components. It means - 256 different c# classes per one world.

**Comment by boris-741** [comment]
can I dynamically create a filter?

**Comment by Leopotam** [comment]
> can I dynamically create a filter?

No, for performance reason - filters should be created during systems registration at ecs-world through dependency injection with attributes or with manual call of GetFilter at constructor of system (you should provide instance of ecs-worlds somehow inside).

Main reason - if you want to create filter, you want to get filtered entities immediately, but its very slow process - scan all entities and validate them for new filter. So, not supported, use predefined filters instead.

> can not filter by predicate only foreach?

I dont understand question. Is filter entities designed for looping only with foreach? No, filter.Entities is standard List<int> collection, you can iterate over it as you want. No, you should not change this collection directly.

**Comment by boris-741** [comment]
I mean find value in a range using lambda for example:
var f_food  = _foodFilter.Entities.Find(el=>_world.GetComponent<Food> (el, _foodId).Coords.X == snakeCoords.X);
Is it safe for the GetComponent to return null?

**Comment by Leopotam** [comment]
if requested filter contains required component - all filtered entities should contains this component (GetComponent should return instance). If not - its a bug.

**Comment by Leopotam** [comment]
@boris-741 for next short questions use [gitter](https://gitter.im/leopotam/ecs), please.
