### ISSUE TITLE
Delete Entity

### ISSUE THREAD

**Issue by DDolG** [Leopotam/ecs#10]
Hi!
When i delete food entity in ecs-snake, i have so much errors. Like this:

Exception: Cant add component on entity 82, already marked as added in mask
Leopotam.Ecs.EcsWorld.ProcessDelayedUpdates () (at Assets/Ecs/Core/EcsWorld.cs:485)
Leopotam.Ecs.EcsSystems.Run () (at Assets/Ecs/Core/EcsSystems.cs:264)
GameStartup.Update () (at Assets/Snake/Scripts/GameStartup.cs:28)

I don't understend? what is wrong?

**Comment by Leopotam** [comment]
> When i delete food entity in ecs-snake

how you did it?

**Comment by DDolG** [comment]
that:
_world.RemoveEntity(_foodFilter.Entities[foodEntityId]);

**Comment by Leopotam** [comment]
> Cant add component on entity 82, already marked as added in mask

its some sort of protection, looks like you not only remove entity, but create something else.

**Comment by Leopotam** [comment]
@DDolG for short questions better to use [gitter chat](
https://gitter.im/leopotam/ecs), public or private.

**Comment by DDolG** [comment]
Thank You

**Comment by Leopotam** [comment]
@DDolG is issue fixed for you or not?

**Comment by Leopotam** [comment]
Closed as solved.
