### ISSUE TITLE
How to control order of execution?

### ISSUE THREAD

**Issue by juhanikarlsson** [Leopotam/ecs#13]
Hi,

How to control order of executing systems?
I have input system that needs to read inputs at specific moment.

Thanks!,
- J

**Comment by Leopotam** [comment]
Order of adding system to `EcsSystems` is order of execution for `IEcsPreInitSystem`, `IEcsInitSystem`, `IEcsRunSystem` methods.

**Comment by juhanikarlsson** [comment]
Makes sense - thanks for clearing that! 
Then it seems to be mysterious bug on my end...

Cheers,
- J

**Comment by Leopotam** [comment]
If you have problem with uGui events on fast clicks in row - you can try to increase amount of processing events at `EventSystem` monobehaviour instance at scene (10 by default, 15-20 should fix issue).

**Comment by Leopotam** [comment]
@juhanikarlsson is this issue still active?

**Comment by juhanikarlsson** [comment]
Hi, 
You can close it! Thanks for the info!

Cheers,
- J
