### ISSUE TITLE
How to notify components tracking an entityid

### ISSUE THREAD

**Issue by purestrain** [Leopotam/ecs#14]
Hi,

what is a possible (maybe not so bad) solution for detecting dangling ids? e.g. if a component has some sort of "targetId" and this corresponding entity gets destroyed? (and its id gets reused)

Edit: Not sure how to add a label like "question"

**Comment by Leopotam** [comment]
Think about entity id as about memory pointers - you should take care about access to removed instances on your side, in ecs its same. There is method `EcsWorld.IsEntityExists()`, but its not 100% protection due to all removed entities can be reused later.

**Comment by purestrain** [comment]
Thank you, I'm wrapping my head around this stuff. If I had an entity object I would register every reference there and call something like "dispose" on it which in turn would remove every reference from other objects. In this case I don't have a entity object. I could iterate through all components when they get removed and call something on it, but I bet this is not the best method. How would you handle a component which references multiple entities like "listOfTargetIds"?

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by Leopotam** [comment]
Why you want to keep links to all entities, can you explain your case?

* In common cases you should work with components and `EcsFilter` - its what you should use for process data inside compatible components and dont cache anything locally.
* If you need to cleanup data fields at components automatically, you should do it manuall before `EcsWorld.RemoveComponent`, or implement `IEcsAutoResetComponent` interface for yur component - then use `Reset` method body as you want for correct cleanup (it described at `README` in FAQ section).
* Another case - you can subscribe to events of `EcsFilter` and remove / add filtered entities to your local cache - you can check [ecs-reactive implementation](https://github.com/Leopotam/ecs-reactive).

Btw, there is [chat about leoecs](https://gitter.im/leopotam/ecs) for short fast questions, link to this chat you can find at `README` too.

**Comment by Leopotam** [comment]
@purestrain is this issue still active?
