### ISSUE TITLE
how to use define multiple same type components

### ISSUE THREAD

**Issue by cloudfreexiao** [Leopotam/ecs#16]
Hi:
May I can multiple same components in one entity ?
[Should entities support multiple instances of the same component?](https://ourmachinery.com/post/should-entities-support-multiple-instances-of-the-same-component/)

**Comment by Leopotam** [comment]
No, only unique typed components, it used for fast searching components on entities and proper filtering found entities by `EcsFilter`-s.

**Comment by Leopotam** [comment]
@cloudfreexiao is answer clear, can I close issue?
