### ISSUE TITLE
Add support for custom package registry

### ISSUE THREAD

**Issue by BenjaminMoore** [Leopotam/ecs#17]
Hi there.
We are working on a public registry of open source packages for Unity https://xcrew.dev/
It would be nice if you could support and update LeoEcs yourself.

For it you need:

1. Create a pair login:hash on the site http://www.htaccesstools.com/htpasswd-generator/
2. Select the scope in which your packages will be placed. (Apparently it is com.leopotam)
3. PM me it and I will add your account
4. Install npm
5. Start the terminal and enter `npm set registry http://xcrew.dev`
6. Enter `npm login`
7. Go to the root of your package in the terminal and enter `npm publish`

All dependencies are resolved automatically by the package manager.
It is necessary to specify the dependencies for additional packages like so
```json
{
    "name": "com.leopotam.ecs-ui",
    "author": "Leopotam",
    "displayName": "LeoECS uGui Bindings",
    "description": "Easy uGui event bindings for LeoECS Entity Component System framework.",
    "unity": "2018.3",
    "version": "2019.2.22",
    "keywords": [
        "leoecs",
        "ecs",
        "performance",
        "ui"
    ],
    "dependencies": {
        "com.leopotam.ecs" : "2019.2.22"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/Leopotam/ecs-ui.git"
    }
}
```

To add registry support to the project, add the following lines to the `manifest.json`
```json
{
  "dependencies": {
  },
  "scopedRegistries": [
    {
      "name": "Unity",
      "url": "https://packages.unity.com",
      "scopes": [
        "com.unity"
      ]
    },
    {
      "name": "XCrew",
      "url": "http://xcrew.dev",
      "scopes": [
        "com"
      ]
    }
  ]
}
```

In the editor it looks like this
![image](https://user-images.githubusercontent.com/5537684/53729500-76babc80-3e86-11e9-8add-7e3a7510102e.png)

My Contacts:

- Email: benjminmoore@gmail.com
- Telegram: https://t.me/benjminmoore
- Skype: benjminmoore

Regards, Oleg

**Comment by Leopotam** [comment]
I still wait for official support of custom unity modules from unitechs. If you want to provide support of open source repos i can only suggest to crawl over their github pages, collect `package.json` files (or automatic generate them) and process local uploading to your registry. It can be done as internal process without requirement of registration. Otherwise it will be another unknown temporary site without support by community.
