### ISSUE TITLE
[wiki] Speed\Performance tests

### ISSUE THREAD

**Issue by echeg** [Leopotam/ecs#2]
Are there any performance/memory comparison tests with Entitas-CSharp?

And I wonder what the requirements for .Net framework. Will the code work on .Net Core2 or one .Net Framework?

**Comment by Leopotam** [comment]
> Are there any performance/memory comparison tests with Entitas-CSharp?

[Some tests](https://github.com/justStand/Generic-Entitas-vs-Code-Gen-Entitas-benchmarks) but they are obsoleted.
[Entities creation test](https://gist.github.com/Leopotam/b6c25c0729dd078a634ae38ccfbdbdcb)
[GetComponent test](https://gist.github.com/Leopotam/3df67acb97dc615a89dccf1dbe4a340e)

Entitas preallocates memory for all components for each entity - my ecs allocates space only for used components (with small preallocation in 6 items for common usage).

> And I wonder what the requirements for .Net framework.

Code written for FW2.0 target with "var" keyword from FW3.5 and default values from FW4.0. It uses `Activator.CreateInstance` by default (can be overrided through api) for instance creation and `Reflection` metadata from types for dependency injection. If it will work on .net core - this ecs framework fully compatible.

**Comment by echeg** [comment]
What you think about create Telegram\Gitter group?

I see Snake example and have one question about architecture. Entitas-CSharp has groups like:

```
        var managroup = context.GetGroup(GameMather.PlayerMana);
        managroup.OnEntityAdded +=  (group, entity, index, component) => SetNewMana(entity);
            
        void SetNewMana(GameEntity e)
        {
               ManaText.text = e.mana.Mana.ToString();
        }
```
Entitas-CSharp Groups = Leopotam-Ecs Filtes? May I call filter outside IEcsSystem?
In snake example all game logic is mixed with the game view and unity game engine. Like:

```
                head = _world.AddComponent<SnakeSegment> (_world.CreateEntity ());
                head.Coords = GetForwardCoords (snake.Body[snake.Body.Count - 1].Coords, snake.Direction);
                head.Transform = GameObject.Instantiate (snake.Body[0].Transform.gameObject).transform;
```

Is it possible to separate all the game logic(no unity3d staff only LeopotamECS + game logic) to dll.
And put this dll to unity project and set callbacks to Groups/Filters changes?

**Comment by Leopotam** [comment]
> What you think about create Telegram\Gitter group?

If you will check badges at `README` page, you will find link to git chat.

> Entitas-CSharp Groups = Leopotam-Ecs Filtes?

Yes, its mix of groups + collectors - simplified version.

> May I call filter outside IEcsSystem?

Filters are local for `EcsWorld` instance and reacts to `AddComponent` / `RemoveComponent` / `UpdateComponent` at same world instance. So, you can create multiple `EcsSystems` groups and process them in any order as you want.

> And put this dll to unity project and set callbacks to Groups/Filters changes?

Yes, it should works through DI to fields with special attributes: `EcsFilterInclude` / `EcsFilterExclude`. You can even use `MonoBehaviour` classes as systems with proper DI of `EcsWorld` / `EcsFilter` fields.
