### ISSUE TITLE
Questions for EcsFilters

### ISSUE THREAD

**Issue by XianWorld** [Leopotam/ecs#23]
1. Does filters limit to 64 in EscWorld?

 /// <summary>
/// List of requested filters.
/// </summary>
protected EcsFilter[] _filters = new EcsFilter[64];

2. When I use GetFilter in system update, I can't get the entity fit the filter which create before. I think you should build up the filter when I create it.

3. And, are there some other tricks of the framework?

**Comment by Leopotam** [comment]
> Does filters limit to 64 in EscWorld?

No, filters amount not limited, internal storage will increase capacity when needed.


> I can't get the entity fit the filter which create before. I think you should build up the filter when I create it.

Filters uses "lazy initialization". It means - they will be created only when needed. If you need some filters, you should add it as filed of system or request through `world.GetFilter<EcsFilter<T1, T2>>` before any related components will be added to entity.


> are there some other tricks of the framework?

Some special cases described at `README`. If there are any other issues / questions - better to ask at discord group (link from `README`): https://discord.gg/5GZVde6

**Comment by Leopotam** [comment]
@XianWorld I think I misunderstood you at 2. Did you read "dependency injection" section at `README`? Main idea - you just describe required filters at fields of your system and ecs-core processes request and dependency injection to compatible fields automatically:
```csharp
class MyComponent1 { }
[EcsInject] // required attribute.
class MySystem : IEcsRunSystem {
    EcsFilter<MyComponent1> _myFilter = null;

    public void Run() {
        // _myFilter will be requested, filled and ready to work here automatically.
    }
}
```
