### ISSUE TITLE
Inspector bug report

### ISSUE THREAD

**Issue by XianWorld** [Leopotam/ecs#24]
When remove an entity and create a new one which reuse the old entity id (it appeared in the old position of last entity in editor ispector), there will raise an error 'Exception: Components cant be obtained from removed entity Entity-3:1'.

Is it a bug, or I make some mistakes?

**Comment by XianWorld** [comment]
Although there is the inspector error, the program is running ok.

**Comment by Leopotam** [comment]
did you tried to update `ecs-unity-integration` package to last one from master branch?

**Comment by XianWorld** [comment]
ok, I will upgrade and test it tomorrow, thx.

**Comment by XianWorld** [comment]
I find my core version is 2019.5.22.

**Comment by Leopotam** [comment]
it was fixed in [2019.7.22](https://github.com/Leopotam/ecs-unityintegration/commit/0077efa4920b2e872acae7d8d941809cf32479ac) version.

**Comment by Leopotam** [comment]
@XianWorld is issue fixed on your side?

**Comment by XianWorld** [comment]
yes, it is fixed, thx.

What do you think about this?
https://youtu.be/yTGhg905SCs

I have studied a lot about Unity DOTS, and I think they will take long time to get it all ready for game developing, but I really love it's performance improvements.
How about the performance about LeoEcs? I think it should match the Unity Ecs without Job and Burst. I also think you should privide some best practice guides for developers to improve the performance.

I'm keeping on developing a brand new MMO/MO framework based on ECS, for witch I learn a lot from Overwatch, and really want to learn from you.

Thx a lot.

**Comment by Leopotam** [comment]
@XianWorld about performance you can [check this repo](https://github.com/Belfegnar/ECS.Examples.Boids). What about jobs, you can [check this one](https://github.com/Leopotam/ecs-threads) - it will work outside of unity in pure c# environment with multithreading support.

> yes, it is fixed, thx.

So, I close this issue then.
