### ISSUE TITLE
Looking for more information

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [Leopotam/ecs#26]
Hello, I have been comparing various ECS systems for Unity and I have a couple of general questions:

- Has this been used in a product that has shipped yet or any other type of publicly available application?
- What differences do you see between this ECS and others such as Entitas or Unity's up and coming native implementation? Any strengths or weaknesses in using this over other ECS systems? What areas of improvement are there?
- With Unity's up and coming ECS implementation, do you foresee continuing development on this into the future?

Thank you for your time!

**Comment by Leopotam** [comment]
@jeffcampbellmakesgames 
> Has this been used in a product that has shipped yet or any other type of publicly available application?

Public sources / releases:
[GTA5 custom wounds mod](https://github.com/SH42913/gunshotwound3)
[Pacman](https://github.com/SH42913/pacmanecs)
[GameJam "Elves vs Dwarfs"](https://globalgamejam.org/2019/games/elves-vs-dwarfs)
[NativesECS](https://alex-kpojb.itch.io/natives-ecs)
[Tower Runner Revenge](https://play.google.com/store/apps/details?id=ru.zlodey.towerrunner20)
[PrincessRun](https://play.google.com/store/apps/details?id=ru.zlodey.princessrun)
[HypnoTap](https://play.google.com/store/apps/details?id=com.ZlodeyStudios.HypnoTap)

Not released / in dev:
[Hattori2](https://www.instagram.com/hattorigame/)

> What differences do you see between this ECS and others such as Entitas or Unity's up and coming native implementation? Any strengths or weaknesses in using this over other ECS systems? What areas of improvement are there?

This framework was developed as competitor for Entitas: similar engine-independent behaviour without codegen, less memory allocations and same / better performance.

**UnityECS** supports only structs, its good and bad at same time. It means - performance only solution, you cant use it as architecture pattern for whole project. **Entitas** powered by classes is multipurpose solution, **LeoECS** follows the same goal.

Strengths:
* Pure C#, no native magic.
* No codegen with generics (intellisense support without problem)
* Small / no boilerplate code (relative to UnityECS).
* Small core codebase.
* Low memory footprint
* Engine agnostic
* Builtin simple DI, no need to use Zenject, etc.

Weaknesses:
* Its slower than native implementation with jobs / burst under unity, jobs can be simulated with [ecs-threads](https://github.com/Leopotam/ecs-threads) extension ([some benches](https://github.com/Belfegnar/ECS.Examples.Boids)).
* No data edit support for unity editor, readonly views (no plans to do this anyway).
* Small community (you can find it with discord link from `README`)

> With Unity's up and coming ECS implementation, do you foresee continuing development on this into the future?

Well, I use it in my own / paid projects, so, development / maintenance will be continued in anyway.

**Comment by jeffcampbellmakesgames** [comment]
Hey, thanks for the quick response and for taking the time to answer my questions!. That in itself inspires a lot of faith that this project is active. I'm taking some time to evaluate different ECS solutions for Unity and this ECS just shot up towards the top of my list. 

I can definitely appreciate that this is a library you use for your own professional work that you've also made available via the MIT license. If I adopt this for my own projects I will absolutely attempt to contribute back :) I'll hop on the discord soon and say hello.

**Comment by Leopotam** [comment]
@jeffcampbellmakesgames can I close issue then?
