### ISSUE TITLE
Running multiple worlds in different threads

### ISSUE THREAD

**Issue by webcoyote** [Leopotam/ecs#27]
First, I just wanted to say thank you for creating a great library! I've really enjoyed working with it as it is well-designed and has very readable code.

My use case is perhaps a bit different than what most people are using Leopotam/ecs for: I'm building a multi-threaded game server, and so plan to run many thousands of game worlds simultaneously instead of just one world in Unity.

I made some code changes that support this use case in my fork, and wanted to ask if this is something you were interested in accepting into your library.

The big change is to pool allocations, so as to avoid multi-threaded race conditions: https://github.com/PlayOneMoreGame/ecs/commit/d4404ca295008cb9170beb872ee0d74b5ad7521d.

This change allows me to return a time value ("sleep time") from game systems so I can run systems less frequently and avoid busy-waiting on game worlds that are not doing anything: https://github.com/PlayOneMoreGame/ecs/commit/3e8f670688b36cd2f45cbcaaccc9a2279f21b259.

And this change creates some editor configuration files so that the formatting style you use stays intact: https://github.com/PlayOneMoreGame/ecs/commit/f814563006753ec567698f5294d1868a726614cb.

If you're interested, I'm glad to turn these into PRs, but understand if you don't want to accept them because there is likely some runtime performance hit for the single-threaded use-case you've built the library to support so far.

**Comment by Leopotam** [comment]
@webcoyote thanks for feedback and suggestions.

> The big change is to pool allocations, so as to avoid multi-threaded race conditions

Idea is good, but your implementation adds performance hit on each add / remove component operation. I think that there is another way to do it - put component types as global singleton class (just for getting unique type index), moving component pools to world, but keep them not in dictionary by type - use linear array with nulls at not used places (trade off between performance and memory consuming). Then all component pools will be local for each world and all additional syncs can be removed. I will think about implementation and maybe show something before next release.

> This change allows me to return a time value ("sleep time") from game systems so I can run systems less frequently and avoid busy-waiting on game worlds that are not doing anything

Its not good idea to change global api for some special case - much better to create custom `IEcsSystem`-group like `EcsSystems` for special processing delays, skip some items based on additional interfaces, etc.

> And this change creates some editor configuration files so that the formatting style you use stays intact

Nice, looks like `vscode-omnisharp` extended supported features. I wrote [extension for custom formatting](https://marketplace.visualstudio.com/items?itemName=Leopotam.csharpfixformat) due vscode-omnisharp didnt support most of features few years ago. I will think about keeping codestyle settings as part of repo.

**Comment by Leopotam** [comment]
@webcoyote can you check [feature/component-pool-thread-safe](https://github.com/Leopotam/ecs/tree/feature/component-pool-thread-safe) branch? Is it looks good for you for thread-safe behaviour?

**Comment by webcoyote** [comment]
Wow -- that was some fast coding! Thanks so much for working on this issue.

All my tests indicate that the code you wrote works. I think the only risk is that -- because types derived from `EcsComponentType<T>` are instantiated when the application is running game code (rather than at startup), there could be a race condition where several threads are initializing different components at the same time. They will race to increment with `EcsComponentPool.ComponentTypesCount++`. It may be enough to use `Interlocked.Increment` instead.

**Comment by Leopotam** [comment]
>  there could be a race condition where several threads are initializing different components at the same time.

Not sure about it - in C# static constructors are thread-safe: https://stackoverflow.com/questions/7095/is-the-c-sharp-static-constructor-thread-safe

**Comment by webcoyote** [comment]
You're right that C# static constructors are thread-safe, but the race condition I'm talking about would be when two different static constructors are being called at the same time from different threads, they could race to incorrectly increment ComponentTypesCount. It's only a conceptual vulnerability; I haven't observed this case in practice.

**Comment by Leopotam** [comment]
@webcoyote
> when two different static constructors are being called at the same time from different threads

its not possible i think, static ctor will be called once on first access to any field of generic class (all accessors will be auto-locked, its guaranteed by runtime).

**Comment by webcoyote** [comment]
[This StackOverflow comment](https://stackoverflow.com/questions/7095/is-the-c-sharp-static-constructor-thread-safe#comment90812674_7095) and [its related code](https://tio.run/##pZJNb8IwDIbP7a@wqh1STVRF0y4gTp20y74kkMY1FDMilaRK3FKE@tu7NC0bHxcEudV2n9d@7dQMUpM2TWGE/IHpzhBuxv7xVzRba@RLGxj7viFOIoU048bAl7/3wb4@WCqxhHcuJAtduEu2j0ncQodhn7RGHYbRlLgmFlrmoSpR0qgMo28tCN@ERPYQ7F844UxsMPpQ25GqHR/IoWCBK6UxsIybEfskmtd3EfiKULcErxswmmaIORvGcdwGHbi@sMm5cOHTVeLu1zstOGHc5sEJ4s@Ebtr67FASeyherkVpGQcbhCSoYAKDYX8CXp9IrC2erfcu2wgqKHlW4AgCeISq9ddrGc/x@Nr6Gqya08uLRWbletV2DCWznetrbpmvSHPWT3TUchc@29vJ5p@6zR9yGqnQEqp/b5rmFw) suggest that there could still be a race condition: the C# type-initializer prevents multiple threads from calling the intializer, but it apparently does not prevent threads from accessing the static fields on a thread while the initializer is being called on a different thread.

In a previous project I was able to solve a similar problem: at program startup, before I had multiple threads running, I used reflection to initialize static classes instead of depending upon the semantics of the C# static-initializer. This was due to the Mono-environment (~3.1) not being thread-safe with respect to type-generation, but it seems the same problem potentially exists here as well, in Microsoft's implementation.

**Comment by Leopotam** [comment]
@webcoyote 
> This StackOverflow comment and its related code 

look carefully on example code - he trying to add sleep at static ctor and only then change static field through method. Users already said that code example is incorrect.

**Comment by webcoyote** [comment]
[Here's some code that demonstrates the problem](https://tio.run/##pZJNb8IwDIbP7a@wqh1STVRF0y4gTp20y74kkMY1FDMilaRK3FKE@tu7NC0bHxcEudV2n9d@7dQMUpM2TWGE/IHpzhBuxv7xVzRba@RLGxj7viFOIoU048bAl7/3wb4@WCqxhHcuJAtduEu2j0ncQodhn7RGHYbRlLgmFlrmoSpR0qgMo28tCN@ERPYQ7F844UxsMPpQ25GqHR/IoWCBK6UxsIybEfskmtd3EfiKULcErxswmmaIORvGcdwGHbi@sMm5cOHTVeLu1zstOGHc5sEJ4s@Ebtr67FASeyherkVpGQcbhCSoYAKDYX8CXp9IrC2erfcu2wgqKHlW4AgCeISq9ddrGc/x@Nr6Gqya08uLRWbletV2DCWznetrbpmvSHPWT3TUchc@29vJ5p@6zR9yGqnQEqp/b5rmFw). I use Sleep to simulate a thread-context switch at the "wrong" time.

**Comment by Leopotam** [comment]
@webcoyote ok, I updated behaviour in repo. Can you check, please, is it good for you?

**Comment by webcoyote** [comment]
Yes, this works, thank you.

**Comment by Leopotam** [comment]
@webcoyote any other suggestions relative to thread-safe usage?

**Comment by webcoyote** [comment]
The great thing about the changes you made is that each world is now isolated from all other worlds, so I believe it is all thread-safe. Also, while I haven't done benchmarking, your changes replace a runtime dictionary lookup with a reference to a static memory object, so I expect it's slightly faster too.

Great stuff, thank you.
