### ISSUE TITLE
Github release could match semver

### ISSUE THREAD

**Issue by favoyang** [Leopotam/ecs#28]
Hi @Leopotam,

Thanks for creating the awesome ecs-related packages. I would like to request make new github release match semver exactly. For example release (git tag) v2019.11.22 for packge.json version=2019.11.22. vx.y.z is a common practice for git tags.

Same request for other ecs packages
- https://github.com/Leopotam/ecs-threads
- https://github.com/Leopotam/ecs-types
- https://github.com/Leopotam/ecs-ui
- https://github.com/Leopotam/ecs-unityintegration

This will also benefit opeupm, an upcoming managed upm registry, which build & publish upm packages based on git tags (that conform semver) automatically.
example for this repo - https://beta.openupm.com/packages/com.leopotam.ecs/
example for automatic publishing - https://beta.openupm.com/packages/com.littlebigfun.addressable-importer/ (search for version history).

**Comment by Leopotam** [comment]
@favoyang I dont understood what you want - semver support in "1.2.3" way or keep it as is with "year.month.day"? If second - last year [all versions were released in this way](https://github.com/Leopotam/ecs/releases). Or you talking about dots in git tags that should be same as version in `project.json`? Then "v" prefix should not be used too, right?

About your npm registry publishing in manual / automatic mode - not sure about it, I already [have my own registry](https://github.com/Leopotam/ecs#as-unity-module-from-npm-registry-experimental) where I can publish / unpublish my packages without issues.

**Comment by favoyang** [comment]
> @favoyang I dont understood what you want - semver support in "1.2.3" way or keep it as is with "year.month.day"? If second - last year [all versions were released in this way](https://github.com/Leopotam/ecs/releases). Or you talking about dots in git tags that should be same as version in `project.json`? Then "v" prefix should not be used too, right?

I understand that using y.m.d is a valid semer (and a smart choice).

I was talking about the git tags (v.x.y.z) could match semver in package.json. For example tag v2019.11.22 (rather than v20191122) for ver 2019.11.22. It's a common practice.

Sorry that I didn't notice the you already bundle this package into your own registry, looks great! 

And the upcoming openupm registry I mentioned will automatic build open source package based on git tags that conforms semver (v.x.y.z or x.y.z) (it already hosting 61 pkgs during the alpha). I would like to include this great packages into the service, if you're happy so, use vx.y.z as further release tags will make it work.

**Comment by Leopotam** [comment]
@favoyang I will use `2019.12.22` format for github tags then.

**Comment by favoyang** [comment]
@Leopotam thanks for the efforts.

The summary:

Packages has been processed correctly.
- https://openupm.com/packages/com.leopotam.ecs/
- https://openupm.com/packages/com.leopotam.ecs-types/
- https://openupm.com/packages/com.leopotam.ecs-unityintegration/

Packages will be processed when a semver git tag is released.
- https://openupm.com/packages/com.leopotam.ecs-ui/
- https://openupm.com/packages/com.leopotam.ecs-threads/

You can explore more additions like [adding a badge](https://openupm.com/docs/adding-badge.html).

[![openupm](https://img.shields.io/npm/v/com.leopotam.ecs?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/com.leopotam.ecs/)

Notice that you can also adding badges for your own registry, if you're cautioned about OpenUPM and preferred to maintain your own registry.

![openupm](https://img.shields.io/npm/v/com.leopotam.ecs?label=npm.leopotam.com&registry_uri=https://npm.leopotam.com)
