### ISSUE TITLE
Matching one or more of a component in a Filter

### ISSUE THREAD

**Issue by phxvyper** [Leopotam/ecs#29]
Is there an efficient way to match one or more of a component, as seen in other ECS frameworks like Ashley, Svelto, and Artemis?

For example, two entities which each have different components, `ComponentA` and `ComponentB`. Is there support to match either of these rather than only one or the other?

**Comment by Leopotam** [comment]
There are filters (described in `README`) with one or more components that should exists on entity (all of them, AND operation) or should not exists on entity (NOT operation):
```csharp
class Component1 {
    public int Id;
}
class Component2 {
    public string Name;
}
class Component3 {
    public int Age;
}
class Test : IEcsRunSystem {
    readonly EcsFilter<Component1> _allComponent1Entities = null;
    readonly EcsFilter<Component1, Component2> _allComponent1withComponent2Entities = null;
    readonly EcsFilter<Component1, Component2>.Exclude<Component3> _allComponent1withComponent2withoutComponent3Entities = null;

    public Run() {
        foreach (var idx in _allComponent1Entities) {
            // processing.
        }
        foreach (var idx in _allComponent1withComponent2Entities) {
            // processing.
        }
        foreach (var idx in _allComponent1withComponent2withoutComponent3Entities) {
            // processing.
        }
    }
}
```

**Comment by phxvyper** [comment]
Those are explicit inclusive right? As in, if I have a filter `EcsFilter<Component1, Component2>`, it will only get entities which have both of those components, and not entities which have either 1 or 2 (but not both)?

**Comment by Leopotam** [comment]
Yes, there are no `OR` operations due to entities filtering will be inefficiently in this way.

**Comment by phxvyper** [comment]
Alright, that answers my questions, thank you.
