### ISSUE TITLE
Handling parent-child entity relationships

### ISSUE THREAD

**Issue by chrispytoes** [Leopotam/ecs#30]
What is the recommended way to model entities which can be parented to another entity? I am not using Unity, but I want a similar functionality. To be able to give an entity a parent, and always add the parent's position and rotation to its children.

I've tried using `EcsEntity` as a component property but that seems to break it. I suppose this could be done manually by storing a parent id, then searching for the parents of every entity on every frame, but that sounds too costly.

Is it possible to store some kind of reference to an entity in a component and read its components from a system?

**Comment by Leopotam** [comment]
@chrispytoes
> I've tried using EcsEntity as a component property but that seems to break it

Why you think that it broken? It should works, you can store `EcsEntity` of children at parent component or parent `EcsEntity` at each child. There is one possible issue - parent or child can be destroyed somewhere and you should check stored entity - is it still valid or not. There is special method for this - `bool EcsEntity.IsAlive()`.

**Comment by chrispytoes** [comment]
@Leopotam Sorry, my fault, something totally unrelated.
