### ISSUE TITLE
KeyNotFoundException on destroy

### ISSUE THREAD

**Issue by h3xb0y** [Leopotam/ecs#33]
при выгрузке игровой сцены с EcsWorld/EcsSystems или остановке игры в редакторе падает ошибка в консоле

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <437ba245d8404784b9fbab9b439ac908>:0)
Leopotam.Ecs.UnityIntegration.EcsWorldObserver.UpdateEntityName (Leopotam.Ecs.EcsEntity entity, System.Boolean requestComponents) (at Library/PackageCache/com.leopotam.ecs-unityintegration@a3ab84f4e28443f8ba66231cb697598277459b8d/Runtime/EditorHelpers.cs:171)
Leopotam.Ecs.UnityIntegration.EcsWorldObserver.Leopotam.Ecs.IEcsWorldDebugListener.OnComponentListChanged (Leopotam.Ecs.EcsEntity entity) (at Library/PackageCache/com.leopotam.ecs-unityintegration@a3ab84f4e28443f8ba66231cb697598277459b8d/Runtime/EditorHelpers.cs:151)
Leopotam.Ecs.EcsEntityExtensions.Destroy (Leopotam.Ecs.EcsEntity& entity) (at Library/PackageCache/com.leopotam.ecs@4e3551121465b502c6a696b07433b0a01d0b555a/src/EcsEntity.cs:254)
Leopotam.Ecs.EcsWorld.Destroy () (at Library/PackageCache/com.leopotam.ecs@4e3551121465b502c6a696b07433b0a01d0b555a/src/EcsWorld.cs:114)
Ecs.GameManager.OnDestroy () 
```

экзепшн минорный т.к. только в дебаге. лечил проверкой на ключ в словаре, мб есть более правильное решение

**Comment by Leopotam** [comment]
@h3xb0y это не минорый эксепшн, этот краш означает, что есть косяк в логике работы с ecs-данными - энтити с компонентом была создана до создания зависимого фильтра, который при своей очистке не может его найти, хотя он там быть обязан. Обычно это происходит при вызове в каком-то произвольном монобехе на старте до инжекта всех фильтров (с ленивой инициализацией) в системы - так делать нельзя, код по работе с ecs-миром должен либо строго вызываться из систем, либо вызываться после инициализации мира и систем. Есть 2 варианта решения:
* Вызвать принудительный инжект данных в системы через `systems.ProcessInjects()`, что вызовет принудительное создание зависимых фильтров через ленивую инициализацию в DI. Делать это нужно строго до работы остальных монобехов, работающих с ecs-миром.
* Во внешнем монобехе дергать нужные фильтры до навешивания компонентов, вызывая их инициализацию через `world. GetFilter(typeof(EcsFilter<C1, C2>))`. Менее предпочтителен, потому что количество зависимых фильтров может быть большим и не все их сможешь прописать во внешнем монобехе.

Самый правильный вариант - четко контролировать порядок инициализации кода: сначала ecs-стартап, потом все остальное.

> т.к. только в дебаге

Вся обработка возможных ошибок прямых или косвенных есть только в `DEBUG` режиме, в `RELEASE` они принудительно вырезаются для увеличения производительности и уменьшения размера кода. Если ошибка падает в дебаге - это четкий сигнал, что она точно есть.

**Comment by h3xb0y** [comment]
разобрался, спасибо!
