### ISSUE TITLE
Idea about OneFrame<T> optimization...

### ISSUE THREAD

**Issue by vrecluse** [Leopotam/ecs#34]
Hi, we are planning to use LeoECS in our project.
After reading the source, It seems that OneFrame<T> and ReactiveSystem may not perform very well in massive amount scenarios.
For example, if I got 10000 moving object, and a system witch reacts to the position update event component of each object, and the update event components should be removed each frame.
But the complexity of removing a component is O(n) for each included filter, and O(n * m) for removing all components, which n is the list size of filter and m is the number of components.
Is it possible to implement RemoveAllComponent method of some type, which the included filters can remove all entities with O(m) complexity?
pseudo code:
before:
```csharp
foreach (var component in componentsToRemove) {
    foreach (var entity in filter) {
        CheckCompatibleAndCallback(entity, component);
    }
}
```
after:
```csharp
    foreach (var entity in filter) {
        RemoveEntityCallCallback(entity);
    }
    filter.Clear();

```

**Comment by Leopotam** [comment]
@vrecluse did you check `develop` branch? `EcsFillter.OnEntityRemove` behaviour changed, `DEBUG` sanity checks - too.
If its not enough for you - you can create custom filters or process them through extensions as you want.
About one-frame components - you forgot that you can have alot of filters with dependency on one-frame components (not only `EcsFilter<YourComponent>`) and you cant cleanup them in simpler way. I can only speedup cleanup builtin filter with `for`-loop instead of `foreach`-loop - it will slightly increase performance, but not so much.

**Comment by Leopotam** [comment]
@vrecluse btw, what are you talking about `ReactiveSystem`? You trying to use `classed-based` version with `ecs-reactive` repo? Its not supported anymore, only `structs-based` version under active development. If you trying to create custom reactive behaviour based on filter events - it will never be fast as naive version based on `IEcsRunSystem`-s.

**Comment by vrecluse** [comment]
> @vrecluse btw, what are you talking about `ReactiveSystem`? You trying to use `classed-based` version with `ecs-reactive` repo? Its not supported anymore, only `structs-based` version under active development. If you trying to create custom reactive behaviour based on filter events - it will never be fast as naive version based on `IEcsRunSystem`-s.

I modified `ReactiveSystem` slightly so that it can work with `struct-based` LeoECS, and passed simple tests.
Is it not encouraged to use it anymore?

**Comment by vrecluse** [comment]
> @vrecluse did you check `develop` branch? `EcsFillter.OnEntityRemove` behaviour changed, `DEBUG` sanity checks - too. 10k items should be processed much faster.
> If its not enough for you - you can create custom filters or process them through extensions as you want.
> About one-frame components - you forgot that you can have alot of filters with dependency on one-frame components (not only `EcsFilter<YourOneFrameComponent>`, but complex with 3-4 constraint filters) and you cant cleanup them in simpler way. I can only speedup cleanup builtin filter with `for`-loop instead of `foreach`-loop - it will slightly increase performance, but not so much.

Ok, I saw that filters maintain EntitiesMap which makes removing entity faster than foreach. Thanks.

**Comment by Leopotam** [comment]
@vrecluse if you use `component-changed` part - it will work fast, but reactive systems with local cache inside - its slow, much better to add some marks on entities and filters it later without additional caching.

**Comment by Leopotam** [comment]
@vrecluse btw, for fast questions there is discord group, you can find link in `README` (badge on top).

**Comment by vrecluse** [comment]
> @vrecluse btw, for fast questions there is discord group, you can find link in `README` (badge on top).

Thanks.
