### ISSUE TITLE
Publish as nuget package?

### ISSUE THREAD

**Issue by dazinator** [Leopotam/ecs#35]
Hi,

I was learning monogame (not using unity) and researching the ECS pattern. I wondered if I could use this in my monogame application directly and it seems I should be able to? If this is the case, for ease of use, would you consider building and publishing this library as a nuget package to nuget.org?

**Comment by Leopotam** [comment]
You can use this framework with monogame without issues, but not from nuget: #19

**Comment by Leopotam** [comment]
@dazinator is it clear for you? Can I close issue?

**Comment by dazinator** [comment]
@Leopotam yep, this can be closed. Although, possibly one thing that could be considered is to distribute it as a "sources" nuget package (nuget package that contains the source code rather than a binary).

https://medium.com/@attilah/source-code-only-nuget-packages-8f34a8fb4738

This would allow source code to be directly integrated / added jnto the host / consumer project.

Aside from that, for anyone else that reads this, the current recommendation is to pull in this repo source code as a git submodule and the main reason for distributing source code rather than a built binary is that the library uses various preprocessor directives to control behavior.

**Comment by Leopotam** [comment]
"As sources" - good one idea, but there are preprocessor directives - you should create different packages for each combination of all supported options. I just dont want to waste time on this. I suggest to just connect this repo as git-module and attach to solution for use in all projects - it will be much easier to update from sources and so on.
