### ISSUE TITLE
Obtaining reference to another entity

### ISSUE THREAD

**Issue by Racso** [Leopotam/ecs#36]
Hello! I may be missing something, but, How can I model a component to have a reference to another entity (or component) in LeoECS?

As a simple example: I need a unit to attack another unit. The attacker can have the `AttackUnitComponent`, which would have some kind of reference to the target unit (e.g. a number representing the victim's Entity Id, or the `Id `in the victim's `UnitComponent`, or something similar) and also a damage value. The `AttackSystem` would process entities with that `AttackUnitComponent` and apply the damage to the victim's `HealthComponent`.

The thing is, I can't find a way for the `AttackSystem` to get the victim Entity based on the Id in the attacker `AttackUnitComponent` in order to apply the damage.

Does it make sense? Is that possible?

Thanks!

EDIT: Forgot to mention: I'm talking about a Pure C# situation. No Unity or other game framework involved.

**Comment by Leopotam** [comment]
@Racso did you get answer at discord chat?

**Comment by Racso** [comment]
Yes, I did. Thanks. Please feel free to close this question.

**Comment by RUSshy** [comment]
It could be useful to post the answer here too, so if someone look for that kind of issue, he'll find the right answer

**Comment by Racso** [comment]
@RUSshy Cool. Let's do it.

Here's a summary of the conclusions I got regarding my question:

1. The reference should be stored as an EcsEntity (not an id): `struct AttackUnitComponent { EcsEntity Target; }`.
2. That reference can be obtained in the System that **sets** the AttackUnitComponent, as it will probably have some filter and some logic to validate the target and set it. So, for example, a `SetAttackTargetSystem` would process the Entities with some filters and set the `AttackUnitComponent` with the corresponding `Target`, and then the `AttackSystem` will read the `Target` and apply the damage.
3. What you should NOT do: You should not store filter indexes in components, as the filter indexes are not stable over uses. In other words, filter indexes can't be used for referencing Entities. You should store the reference to the EcsEntity directly.

Some extra conclusions regarding what I'm doing (but not my specific question):
1. You can model a unit damaging several targets with new entities having components that model "events": `struct Attack { EcsEntity Attacker; EcsEntity Target; }` (instead of adding `struct AttackUnitComponent { EcsEntity Target; }` to the attacker).
2. Something similar could be modeled like this: `struct AttackUnitComponent { List<EcsEntity> Targets; }`. In that case, it would be good to add a custom autoreset behavior to the component (as described in the [FAQ](https://github.com/Leopotam/ecs)).

**Comment by RUSshy** [comment]
Thanks!
