### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by nxtht** [Leopotam/ecs#37]
Hi, I was adopting Leoecs in my project and I believe there is a way to slightly improve performance. Now filters have references to component pools in order to get component arrays. Instead, filters can have direct references to these arrays to optimize memory usage.

**Comment by Leopotam** [comment]
@nxtht can you check `develop` branch?

**Comment by Leopotam** [comment]
@nxtht looks good for you?

**Comment by Leopotam** [comment]
@nxtht looks like it works. if no - I will reopen it on request.

**Comment by nxtht** [comment]
Hi, @Leopotam.
It works. I made a repo with benchmarks in case you might be interested
https://github.com/nxtht/ecs.benchmark
