### ISSUE TITLE
EcsComponentRef 

### ISSUE THREAD

**Issue by snailUp** [Leopotam/ecs#38]
If the Equals method of EcsComponentRef is is, it will cause an infinite loop

**Comment by Leopotam** [comment]
@snailUp behaviour changed to `AreEquals()` method:
```csharp
EcsComponentRef<C1> aRef, bRef;
var equals = EcsComponentRef<C1>.AreEquals(aRef, bRef);
```
Can you check that it works on your side?

**Comment by snailUp** [comment]
Okay, I saw AreEquals, thank you very much

**Comment by Leopotam** [comment]
@snailUp will be in next `2021.3.22` release.
