### ISSUE TITLE
Add `EcsWorld.GetEntities()` and `EcsWorld.GetEntityComponents(EcsEntity)`

### ISSUE THREAD

**Issue by Byteron** [Leopotam/ecs#42]
I'd love to see helper functions like this for building a visual debugger in the engine I am using this with.
With those functions I could fetch all the data I need to build a Tree that can be inspected, that lists all entities with their components.

**Comment by Leopotam** [comment]
For debug purposes you should implement [IEcsWorldDebugListener](https://github.com/Leopotam/ecs/blob/master/src/EcsWorld.cs#L481) for your listener and subscribe it to world events with [EcsWorld.AddDebugListener()](https://github.com/Leopotam/ecs/blob/master/src/EcsWorld.cs#L84). If you want to get component values - there is special method [EcsEntity.GetComponentValues()](https://github.com/Leopotam/ecs/blob/master/src/EcsEntity.cs#L522).

**Comment by Leopotam** [comment]
@Byteron is it clear? Can I close issue?

**Comment by caxapexac** [comment]
I'd like to see EcsWorld.GetEntities or something like this too (world serialization purposes, not debug)
Or more clear method returning GetFilter with non-generic filter with all entities

**Comment by SH42913** [comment]
> Or more clear method returning GetFilter with non-generic filter with all entities

Why doesn't simply add a marker component to desired entities and use a filter with marked entities?

**Comment by Leopotam** [comment]
@caxapexac 
> I'd like to see EcsWorld.GetEntities

I can add method, but you cant change world inside loop over returned collection (create / destroy entities) - is it will work for you?

**Comment by caxapexac** [comment]
> You cant change world inside loop over returned collection (create / destroy entities) - is it will work for you?

Yeah sounds legit
(Of cource, there should be comments/exceptions inside the method to prevent users to change it)

**Comment by Leopotam** [comment]
`EcsWorld.GetAllEntities()` method was added (`#develop` branch).
