### ISSUE TITLE
How to filter or find entities based on component data

### ISSUE THREAD

**Issue by hejiang123** [Leopotam/ecs#47]
For example, I have a component A with data X. I want to filter the entities with component A and X equal to 0. Can you only get an entity list through the filter component and handle it by yourself? If the algorithm is carried out frequently in the case of many entities, will it be very slow

**Comment by Leopotam** [comment]
You cant filter components based on their content. I suggest to use empty components as flags for special cases if you need to filter them.
> If the algorithm is carried out frequently in the case of many entities, will it be very slow
It will be much slower for filtering it on core side due to requirement for checks on each change / frame.

**Comment by Leopotam** [comment]
@hejiang123 is it clear? Can I close issue?
