### ISSUE TITLE
How to deal with references to components and entities

### ISSUE THREAD

**Issue by hejiang123** [Leopotam/ecs#51]
I now have a player entity that may have a skill component, and there may be a skill collision entity when a skill is released. And referenced by the skill component. Skill entities are removed when a collision occurs. How should I clean up references to skill components at this time? My current approach is to also store a owning player entity on the skill entity, but it's confusing to reference too many

**Comment by Leopotam** [comment]
@hejiang123 you cant save refs as struct fields directly with proper detection of end of life, its limit of c#. But you can save `EcsEntity` with required components with additional check `entity.IsAlive()` before `entity.Get<>()`.

**Comment by Leopotam** [comment]
If you want just to automate fields clearing on component removement, there are 2 behaviours:
1. default: all fields will be automatically reset to default values.
2. custom IEcsAutoReset handler - you can manage clearing process.

**Comment by Leopotam** [comment]
@hejiang123 is it clear? Can I close issue?

**Comment by hejiang123** [comment]
okay, thank you
