### ISSUE TITLE
Moving/Copying entities between worlds

### ISSUE THREAD

**Issue by Itay2805** [Leopotam/ecs#53]
Is there a way to move entities between worlds?

Currently I do it with just serializing all of the entities and then deserializing them, but I was hoping there would be a faster way to do that...

**Comment by Leopotam** [comment]
@Itay2805 its not possible in common way due to components list can be different at each world. It means - you should copy required (and well known by you) data on your side.

**Comment by Itay2805** [comment]
I see, so for now I will do something similar to the serialize/deserialize (I use the GetEntities and GetComponentValues/GetComponentTypes and use reflection to use the generic with a Type rather than a compile time known generic)
