### ISSUE TITLE
Getting StackOverflowException by using EcsFilter<>.Optimize()

### ISSUE THREAD

**Issue by Satan1c** [Leopotam/ecs#57]
Делаю обычный класс для генерации тайлов земли, но после использования 
https://github.com/Leopotam/ecs/blob/389f8b32b3a3e222c4a50eda3541d7d5e2e2d5a3/src/EcsFilter.cs#L350

в
```cs
public class GroundSystem : IEcsInitSystem, IEcsPreInitSystem
{
    public EcsWorld _World = null;
    public EcsFilter<Ground> _grounds = null;

    public void PreInit() { . . . }

    public void Init()
    {
        if (_grounds.IsEmpty())
            return;

        _grounds.Optimize();
    }
}
```
получаю ошибку StackOverflowException.

**Comment by Leopotam** [comment]
@Satan1c просто не используй этот метод, оно никогда и ни кем не использовалось, достаточно не тестировалось и его создание было ошибкой. Помечу как `[obsolete]`.

**Comment by Leopotam** [comment]
@Satan1c кодоген фильтров обновлен, сами фильтры обновлены, метод `Optimize()` удален - можно попробовать в `#develop` бранче, в релизе будет 22 февраля.
