### ISSUE TITLE
how to detect more than 4 components?

### ISSUE THREAD

**Issue by kkohno** [Leopotam/ecs#6]
Built in Filters can give maximum 4 components. But  what if i need check for another type of component?

**Comment by Leopotam** [comment]
@kkohno check `README` first.

**Comment by Leopotam** [comment]
If you need just check - "are there any other components on filtered entities", you can touch them with `GetComponent` method. If you need filtering for entities that 100% contains 5-8-10-etc components - you should create custom filter. You can open `EcsFilter.cs` at ECS sources file and copy&paste one of generic filters to your file, then add new components support.

**Comment by kkohno** [comment]
hanks for the quick and useful answer.

**Comment by Leopotam** [comment]
So, issue solved, can be closed?

**Comment by kkohno** [comment]
yes, thanks
