### ISSUE TITLE
Injecting SO

### ISSUE THREAD

**Issue by xahon** [Leopotam/ecs#7]
Hi.
Is there a way to inject scriptable object preferences into my systems or I should use something like FindObjectOfType<SO_Holder>().MySO?

**Comment by xahon** [comment]
Or I should use startup with inspector liks and pass-throught them into system via ctor?

**Comment by Leopotam** [comment]
@xahon you can attach your SO at field of startup script and then provide it somehow to ecs systems (through constructor to proper systems or with EcsFilterSingle) - you can find example at [ecs-ui example repo](https://github.com/Leopotam/ecs-ui.examples/blob/master/Assets/Examples/Startup.cs).

Another way to do it - load SO from `Resources` folder and use it as described before (without instantiation).

**Comment by Leopotam** [comment]
@xahon if you dont like ctor DI idea, you can create ecs component with fields of all required SO assets and share it through `EcsFilterSingle`. Example of this behaviour described at [README](https://github.com/Leopotam/ecs#sharing-data-between-systems).

**Comment by xahon** [comment]
@Leopotam  Don't ctor DI damage on unit testing in project?

**Comment by Leopotam** [comment]
@xahon it depends on how you will write tests. SO - is just c# class on your side and you even can use some custom mockup data class for required simulation.
